@startuml

skinparam classAttributeIconSize 0

class Account {
    - id: String
    - password: String

    + login(): boolean
    + findIdPassword(): void
}

class User {
    - visitHistory: List<int>
    - favoriteMovies: List<Movie>

    + addVisitHistory(int): void
    + deleteVisitHistory(int): void
    + addReview(Review): void
    + deleteMyReview(Review): void
    + addFavoriteMovie(Movie): void
    + deleteFavoriteMovie(Movie): void
}

class Admin {
    + addMovie(Movie): void
    + updateMovie(Movie): void
    + deleteMovie(Movie): void
    + deleteUserReview(Review): void
}

class Review {
    - reviewId: int
    - authorId: int
    - movieId: int
    - content: String
}

class Movie {
    - movieId: int
    - title: String
    - releaseDate: Date
    - runtime: int
    - genreIds: List<int>
    - overview: String
    - rateAvg: float
    - rateCount: int
    - directorId: int
    - actorIds: List<int>
    - companyId: int
    - reviewIds: List<int>
    - posterPath: String
    - backdropPath: String
    - popularity: float

    + getInfo(): json
    + getDetails(): json
    + getReviews(Movie): List<Review>
    + getRelatedMovies(): List<Movie>
}

class MovieSearch {
    + searchByKeyword(keyword: String): List<Movie>
}

class MovieRecommendation {
    + getRecentMovies(): List<Movie>
    + getPopularMovies(): List<Movie>
    + getMoviesByGenre(genreId: int): List<Movie>
}

Account ^-- User
Account ^-- Admin

User --> Movie
User --> Review

Admin --> Movie
Admin --> Review

Movie --> Review

MovieSearch --> Movie

MovieRecommendation --> Movie

@enduml
