@startuml

skinparam classAttributeIconSize 0

class Account {
    - id: int
    - accountType: int

    + login(id: String, password: String): boolean
}

class User {
    - visitHistory: List<Movie>
    - favoriteMovies: List<Movie>
    - myReviews: List<Review>

    + addVisitHistory(movieId: int): boolean
    + deleteVisitHistory(movieId: int): boolean
    + addReview(Review): boolean
    + deleteMyReview(reviewId: int): boolean
    + addFavoriteMovie(movieId: int): boolean
    + deleteFavoriteMovie(movieId: int): boolean
}

class Admin {
    + addMovie(Movie): boolean
    + updateMovie(Movie): boolean
    + deleteMovie(movieId: int): boolean
    + deleteUserReview(reviewId: int): boolean
}

class Review {
    - reviewId: int
    - authorId: int
    - movieId: int
    - content: String
}

class Movie {
    - movieId: int
    - title: String
    - releaseDate: Date
    - runtime: int
    - genreIds: List<int>
    - overview: String
    - rateAvg: float
    - rateCount: int
    - directorId: int
    - actorIds: List<int>
    - companyId: int
    - reviewIds: List<int>
    - posterPath: String
    - backdropPath: String
    - popularity: float
}

class MovieSearch {
    + searchByKeyword(keyword: String): List<Movie>
}

class MovieRecommendation {
    - recentMovieList: List<Movie>
    - popularMovieList: List<Movie>
    - movieListByGenre: List<Movie>
}

Account ^-- User
Account ^-- Admin

User --> Movie
User --> Review
User ..> MovieRecommendation
User ..> MovieSearch

Admin ..> Movie
Admin ..> Review
Admin ..> MovieRecommendation
Admin ..> MovieSearch

Movie *-- Review

MovieSearch ..> Movie

MovieRecommendation --> Movie

@enduml
