@startchen

entity "Account" as ACCOUNT {
}

entity "User" as USER {
}

entity "Admin" as ADMIN {
}

entity "Movie" as MOVIE {
}

entity "Director" as DIRECTOR {
}

entity "Actor" as ACTOR {
}

entity "Company" as COMPANY {
}

entity "Review" as REVIEW <<weak>> {
}

entity "Favorite Movie" as FAVORITE_MOVIE <<weak>> {
}

entity "Visited Movie" as VISITED_MOVIE <<weak>> {
}

ACCOUNT ->- U { USER, ADMIN }

' Relationships
relationship "favorites" as FAVORITES <<identifying>> {
}

relationship "visits" as VISITS <<identifying>> {
}

relationship "writes" as WRITES <<identifying>> {
}

relationship "has reviews" as HAS_REVIEWS <<identifying>> {
}

relationship "directed by" as DIRECTED_BY {
}

relationship "has actors" as HAS_ACTORS {
}

relationship "produced by" as PRODUCED_BY {
}

FAVORITES -1- USER
FAVORITES =N= FAVORITE_MOVIE

VISITS -1- USER
VISITS =N= VISITED_MOVIE

WRITES -1- USER
WRITES =N= REVIEW

HAS_REVIEWS -1- MOVIE
HAS_REVIEWS =N= REVIEW

DIRECTED_BY -N- MOVIE
DIRECTED_BY -1- DIRECTOR

HAS_ACTORS -M- MOVIE
HAS_ACTORS -N- ACTOR

PRODUCED_BY -N- MOVIE
PRODUCED_BY -1- COMPANY

@endchen
