@startuml

actor "사용자" as user
participant "메인 페이지" as mainPage
participant "상세 정보 페이지" as detailPage
database "영화 DB" as db

user -> mainPage : 영화 선택
activate mainPage
mainPage -> detailPage : 상세 정보 페이지 이동
deactivate mainPage
activate detailPage

detailPage -> db : 영화 상세 정보 요청
activate db
db --> detailPage : 영화 상세 정보 반환
deactivate db
detailPage --> user : 상세 정보 출력
deactivate detailPage

@enduml
