@startuml

actor "관리자" as admin
participant "관리자 페이지" as adminPage
database "영화 DB" as db

admin -> adminPage : 영화 정보 등록
activate adminPage
adminPage -> db : 영화 정보 저장
activate db
db --> adminPage : 영화 정보 저장 완료
deactivate db
adminPage --> admin : 영화 정보 등록 완료
deactivate adminPage

admin -> adminPage : 영화 선택
activate adminPage
adminPage -> db : 영화 정보 요청
activate db
db --> adminPage : 영화 정보 반환
deactivate db
adminPage --> admin : 영화 정보 출력
admin -> adminPage : 영화 정보 수정
adminPage -> db : 영화 정보 수정 요청
db --> adminPage : 영화 정보 수정 완료
adminPage --> admin : 영화 정보 수정 완료
deactivate adminPage

admin -> adminPage : 영화 정보 삭제
activate adminPage
adminPage -> db : 영화 정보 삭제 요청
activate db
db --> adminPage : 영화 정보 삭제 완료
deactivate db
adminPage --> admin : 영화 정보 삭제 완료
deactivate adminPage

@enduml
