@startuml

actor "사용자" as user
participant "상세 정보 페이지" as detailPage
database "리뷰 DB" as db

user -> detailPage : 영화 선택
activate detailPage
detailPage -> db : 리뷰 목록 요청
activate db
db --> detailPage : 리뷰 목록 반환
deactivate db
detailPage --> user : 리뷰 목록 출력
deactivate detailPage

user -> detailPage : 리뷰 입력
activate detailPage
detailPage -> db : 리뷰 저장
activate db
db --> detailPage : 리뷰 저장 완료
deactivate db
detailPage -> db : 리뷰 목록 요청
activate db
db --> detailPage : 최신 리뷰 목록 반환
deactivate db
detailPage --> user : 리뷰 목록 출력
deactivate detailPage

user -> detailPage : 리뷰 삭제
activate detailPage
detailPage -> db : 리뷰 삭제 요청
activate db
db --> detailPage : 리뷰 삭제 완료
deactivate db
detailPage -> db : 리뷰 목록 요청
activate db
db --> detailPage : 최신 리뷰 목록 반환
deactivate db
detailPage --> user : 리뷰 목록 출력
deactivate detailPage

@enduml
