@startuml

actor "사용자" as user
participant "로그인 시스템" as login
database "계정 DB" as db

user -> login : 아이디, 비밀번호 입력
activate login
login -> db : login(id: String, password: String)
activate db

db --> login : 로그인 정보 반환
deactivate db

alt 로그인 성공
login --> user : 로그인 성공 시 홈 화면 이동
else 로그인 실패
  login --> user : 로그인 실패 시 재시도 요청
deactivate login
end

@enduml
