@startuml

actor "사용자" as user
participant "마이 페이지" as myPage
database "방문 기록 DB" as db

user -> myPage : 마이 페이지 접속
activate myPage
myPage -> db : 방문 기록 요청
activate db
db --> myPage : 방문 기록 반환
deactivate db
myPage --> user : 방문 기록 출력
deactivate myPage

user -> myPage : 방문 기록 삭제
activate myPage
myPage -> db : deleteVisitHistory(movieId: int)
activate db
db --> myPage : 방문 기록 삭제 완료
deactivate db
myPage -> db : 방문 기록 요청
activate db
db --> myPage : 방문 기록 반환
deactivate db
myPage --> user : 방문 기록 출력
deactivate myPage

@enduml
