@startuml

[*] --> 메인페이지

state 메인페이지 {
  [*] --> 탐색

  탐색 --> 로그인 : 로그인

  탐색 --> 로그아웃
  로그아웃 --> 탐색 : 로그아웃

  탐색 --> 검색중 : 검색어 입력
  검색중 --> 탐색 : 검색 결과 보기

  탐색 --> 상세정보페이지 : 영화 선택
  상세정보페이지 --> 탐색 : 목록으로 돌아가기

  탐색 --> [*]
}

state 로그인 {
  [*] --> 대기

  대기 --> 계정정보검증 : 계정정보 입력

  계정정보검증 --> 성공 : 계정정보 유효
  계정정보검증 --> 오류 : 계정정보 무효

  오류 --> 대기 : 계정정보 재입력
  성공 --> 메인페이지
}

state 상세정보페이지 {
  [*] --> 상세보기
  상세보기 --> 리뷰작성 : 리뷰 작성
  리뷰작성 --> 상세보기 : 리뷰 제출됨
  상세보기 --> 관심영화등록 : 관심영화에 등록
  관심영화등록 --> 상세보기 : 영화 등록됨
}

state 관리자패널 {
  [*] --> 조작

  영화관리중 --> 조작 : 영화 추가/삭제/수정
  조작 --> 영화관리중

  리뷰관리중 --> 조작 : 리뷰 삭제
  조작 --> 리뷰관리중
}

로그인 --> 메인페이지 : 돌아가기

메인페이지 --> 관리자패널 : 관리자 접근
관리자패널 --> 메인페이지 : 관리자 패널 종료

@enduml
