@startuml state

[*] --> 메인페이지
메인페이지 -->[*]
메인페이지 --> 로그인
로그인 --> 관리자_페이지

관리자_페이지 --> 관리자_영화검색
관리자_페이지 --> 영화등록

관리자_영화검색 --> 리뷰삭제
관리자_영화검색 --> 영화정보_수정
관리자_영화검색 --> 영화정보_삭제

메인페이지 --> 영화조회
메인페이지 --> 영화검색

영화조회 --> 계정정보확인
영화검색 -->계정정보확인

계정정보확인 --> 방문기록추가

계정정보확인 --> 영화_상세정보_페이지 : 로그인X
방문기록추가 --> 영화_상세정보_페이지

영화_상세정보_페이지 --> 리뷰_등록_삭제_요청
리뷰_등록_삭제_요청 --> 영화_상세정보_페이지

리뷰_등록_삭제_요청 --> 리뷰_계정정보_확인
리뷰_계정정보_확인 --> 리뷰_등록_삭제_요청

리뷰_계정정보_확인 --> 영화_상세정보_페이지

state 로그인 {
  [*] --> 대기

  대기 --> 계정정보검증 : 계정정보 입력

  계정정보검증 --> 사용자_성공 : 계정정보 유효
  계정정보검증 --> 관리자_성공 : 계정정보 유효
  계정정보검증 --> 오류 : 계정정보 무효

  오류 --> 대기 : 계정정보 재입력
  사용자_성공 --> 메인페이지
  관리자_성공 --> 관리자_페이지
}

@enduml
