@startuml state

[*] --> 메인페이지
메인페이지 --> [*]

메인페이지 --> 마이페이지 : accountType == 0

마이페이지 --> 관심영화관리
관심영화관리 --> 마이페이지

메인페이지 --> 영화_상세정보
영화_상세정보 --> 메인페이지

메인페이지 --> 영화검색

메인페이지 --> 관리자 : accountType == 1

메인페이지 --> 로그인
로그인 --> 메인페이지

마이페이지 --> 방문기록
방문기록 --> 마이페이지

영화_상세정보 --> 리뷰등록 : accountType == 0
리뷰등록 --> 영화_상세정보

영화_상세정보 --> 관심등록 : accountType == 0
관심등록 --> 영화_상세정보

관리자 --> 리뷰삭제
리뷰삭제 --> 관리자

관리자 --> 영화관리
영화관리 --> 관리자


영화검색 --> 영화_상세정보

마이페이지 : entry/ 마이페이지 이동
마이페이지 : do/ 작업선택
마이페이지 : exit/ 선택작업 화면이동

메인페이지 : entry/ 메인페이지 이동
메인페이지 : do/ 작업선택
메인페이지 : exit/ 선택작업 화면이동

관심영화관리 : do/ 관심영화 삭제
관심영화관리 : exit/ 관심영화DB 업데이트

방문기록 : do/ 방문기록 삭제
방문기록 : exit/ 방문기록DB 업데이트

리뷰등록 : do/ 리뷰작성
리뷰등록 : exit/ 리뷰DB 업데이트

관심등록 : do/ 관심등록
관심등록 : exit/ 관심DB 업데이트

영화검색 : entry/ 검색요청
영화검색 : do/ DB 검색
영화검색 : exit/ 목록 반환

관리자 : entry/ 관리자페이지 이동
관리자 : do/ 작업선택
관리자 : exit/ 선택작업 화면 이동

리뷰삭제 : do/ 리뷰삭제
리뷰삭제 : exit/ 리뷰DB 업데이트

영화관리 : do/ 영화 등록/삭제/수정
영화관리 : exit/ 영화DB 업데이트

영화_상세정보 : entry/ 영화 선택
영화_상세정보 : do/ DB 검색
영화_상세정보 : exit/ 상세정보 반환
@enduml
